export const LANGUAGES = [
  { label: '中文 (Chinese)', code: 'zh' },
  { label: '日本語 (Japanese)', code: 'ja' },
  { label: '한국어 (Korean)', code: 'ko' },
  { label: 'ไทย (Thai)', code: 'th' },
  { label: 'Български (Bulgarian)', code: 'bg' },
  { label: 'Čeština (Czech)', code: 'cs' },
  { label: 'Dansk (Danish)', code: 'da' },
  { label: 'Deutsch (German)', code: 'de' },
  { label: 'English', code: 'en' },
  { label: 'Español (Spanish)', code: 'es' },
  { label: 'Ελληνικά (Greek)', code: 'el' },
  { label: 'Français (French)', code: 'fr' },
  { label: 'Italiano (Italian)', code: 'it' },
  { label: 'Bahasa Indonesia (Indonesian)', code: 'id' },
  { label: 'Magyar (Hungarian)', code: 'hu' },
  { label: 'Nederlands (Dutch)', code: 'nl' },
  { label: 'Norsk (Norwegian)', code: 'no' },
  { label: 'Polski (Polish)', code: 'pl' },
  { label: 'Português (Portuguese)', code: 'pt' },
  { label: 'Română (Romanian)', code: 'ro' },
  { label: 'Русский (Russian)', code: 'ru' },
  { label: 'Suomi (Finnish)', code: 'fi' },
  { label: 'Svenska (Swedish)', code: 'sv' },
  { label: 'Türkçe (Turkish)', code: 'tr' },
  { label: 'Tiếng Việt (Vietnamese)', code: 'vi' },
  { label: 'Українська (Ukrainian)', code: 'uk' },
] as const;

export const GAME_PLATFORMS = [
  { label: 'PlayStation 5', code: 'ps5' },
  { label: 'PlayStation 4', code: 'ps4' },
  { label: 'Xbox Series X', code: 'xbox-series' },
  { label: 'Nintendo Switch', code: 'ns' },
  { label: 'Nintendo Switch 2', code: 'ns2' },
  { label: 'PC', code: 'pc' },
  { label: 'Mobile', code: 'mobile' },
  { label: 'Web', code: 'web' },
] as const;
