import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { Resvg } from '@resvg/resvg-js'

/**
 * Build every site icon from one source: `server/assets/brand/logo.svg`, the
 * vector trace of the brand mark.
 *
 * Run with `pnpm generate:icons` after the brand art changes. Outputs:
 *
 *   public/logo.svg             the mark itself, for the header and in-page use
 *   public/favicon.svg          the tab cut — modern browsers scale this one
 *   public/favicon.ico          16/32/48, for browsers that ask for /favicon.ico
 *   public/apple-touch-icon.png 180×180 on an opaque ground, for iOS
 *
 * ## Why the tab cut differs from the mark
 *
 * The mark is wide and short — its ink fills the canvas across but only the
 * middle two thirds down — so dropped into a square tab slot it renders about
 * 16×11, and the outline's thin passages land on a fraction of a pixel. The tab
 * cut therefore centres the ink in a square viewBox, adds weight to the outline
 * and enlarges the four buttons. That is ordinary optical sizing: a favicon is a
 * separate cut of a mark, not the same file shrunk.
 */

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const source = await readFile(join(root, 'server/assets/brand/logo.svg'), 'utf8')

/** The artwork without its provenance comment, which each output re-states itself. */
const artwork = source.replace(/<!--[\s\S]*?-->\s*/, '').trim()

const banner = (what) => `<!-- ${what} Generated by scripts/generate-icons.mjs from server/assets/brand/logo.svg — do not edit by hand. -->\n`

/**
 * Ink bounds of the mark inside its 256 viewBox, measured off the source art:
 * it spans the full width but sits high, ending at y≈208 of 256.
 */
const INK_TOP = 34.5
const INK_BOTTOM = 208.5

/**
 * The tab cut, in a square viewBox so no consumer can stretch it: the ink is
 * nudged to the vertical centre, the outline carries an extra stroke on top of
 * its filled path, and the buttons grow from the mark's own r≈8.5.
 *
 * `prefers-color-scheme` is honoured by browsers that take SVG favicons, which
 * matters because the mark is drawn in black and tab strips go dark.
 */
function tabCut() {
  const shift = 128 - (INK_TOP + INK_BOTTOM) / 2
  const inner = artwork
    .replace(/^<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace('<path d=', '<path class="ink" stroke="#000000" stroke-width="6" stroke-linejoin="round" d=')
    .replace(/<rect /g, '<rect class="ink" ')
    .replace(/r="[\d.]+"/g, 'r="10.5"')
    .trim()

  return `${banner('PSRay tab icon.')}<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" role="img" aria-label="PSRay">
  <style>
    @media (prefers-color-scheme: dark) {
      .ink { fill: #ffffff; stroke: #ffffff; }
    }
  </style>
  <g transform="translate(0 ${shift.toFixed(1)})">
${inner.split('\n').map(line => `  ${line}`).join('\n')}
  </g>
</svg>
`
}

/** Rasterise an SVG string to a square PNG of `size` px. */
const rasterize = (svg, size) =>
  Buffer.from(new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render().asPng())

/**
 * Pack PNGs into an ICO. Every entry is PNG-encoded, which every browser still
 * asking for `/favicon.ico` has understood for well over a decade.
 */
function ico(images) {
  const header = Buffer.alloc(6)
  header.writeUInt16LE(0, 0)
  header.writeUInt16LE(1, 2)
  header.writeUInt16LE(images.length, 4)

  const directory = Buffer.alloc(images.length * 16)
  let offset = header.length + directory.length
  images.forEach(({ size, data }, index) => {
    const entry = index * 16
    directory[entry] = size >= 256 ? 0 : size
    directory[entry + 1] = size >= 256 ? 0 : size
    directory.writeUInt16LE(1, entry + 4)
    directory.writeUInt16LE(32, entry + 6)
    directory.writeUInt32LE(data.length, entry + 8)
    directory.writeUInt32LE(offset, entry + 12)
    offset += data.length
  })

  return Buffer.concat([header, directory, ...images.map(image => image.data)])
}

/**
 * iOS neither reads SVG nor keeps transparency — a transparent icon lands on a
 * black home screen tile — and it masks the corners itself, so the mark is
 * inset on an opaque ground rather than run to the edge.
 */
function appleTouch(size = 180) {
  const inset = Math.round(size * 0.14)
  const width = size - inset * 2
  const height = Math.round(width * (INK_BOTTOM - INK_TOP) / 256)
  const mark = artwork
    .replace(/^<svg[^>]*>/, `<svg xmlns="http://www.w3.org/2000/svg" x="${inset}" y="${Math.round((size - height) / 2)}" width="${width}" height="${height}" viewBox="0 ${INK_TOP} 256 ${INK_BOTTOM - INK_TOP}">`)

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" fill="#ffffff"/>
  ${mark}
</svg>`
}

const tab = tabCut()
const written = []
const write = async (name, data) => {
  await writeFile(join(root, 'public', name), data)
  written.push(`${name} — ${(data.length / 1024).toFixed(1)}KB`)
}

await write('logo.svg', `${banner('PSRay brand mark.')}${artwork}\n`)
await write('favicon.svg', tab)
await write('favicon.ico', ico([16, 32, 48].map(size => ({ size, data: rasterize(tab, size) }))))
await write('apple-touch-icon.png', rasterize(appleTouch(), 180))

console.log(written.join('\n'))
